version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
      - "5050:5050"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mongo
    volumes:
      - db_data:/data/db

volumes:
  db_data:
